<?php

class Pspao_akhir_model extends CI_Model {
    
  
public function get_kementerian(){
	$this->db->select('idkem, namakem');
	$this->db->order_by("namakem", "ASC");
	$query = $this->db->get('lkp_kementerian');
	$kementerian = array();
	
	if($query->result()){
    	$kementerian[''] = '- Pilih Kementerian -';
		foreach ($query->result() as $kem){
        	$kementerian[$kem->idkem] = $kem->namakem;
		}
		return $kementerian;
	}
} 
 
public function get_jabatan(){
	$this->db->select('idjab_agensi_myspata1, nama_jab_agensi');
	$this->db->order_by("nama_jab_agensi", "ASC");
	$query = $this->db->get('lkp_jab_agensi');
	$jabatan = array();
	
	if($query->result()){
    	$jabatan[''] = '- Pilih Kementerian -';
		foreach ($query->result() as $jab){
        	$jabatan[$jab->idjab_agensi_myspata1] = $jab->nama_jab_agensi;
		}
		return $jabatan;
	}
} 

public function get_status(){
   	$this->db->select('status_id, nama_status');
   	$this->db->order_by("nama_status", "ASC");
   	$query = $this->db->get('lkp_status');
	$status = array();
	
	if($query->result()){
		$status[''] = '- Pilih Status -';
        foreach ($query->result() as $sta){
        	$status[$sta->status_id] = $sta->nama_status;
        }
      	return $status;
	}
}   

public function get_data_dummy(){
	
	$data_1 =   array(
					array('1','PSPAO000001','2013','Kementerian','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href=""><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  	array('2','PSPAO000002','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('3','PSPAO000003','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('4','PSPAO000004','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('5','PSPAO000005','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('6','PSPAO000006','2013','Agensi','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('7','PSPAO000007','2013','Kementerian','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('8','PSPAO000008','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('9','PSPAO000009','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('10','PSPAO000010','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('11','PSPAO000011','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('12','PSPAO000012','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('13','PSPAO000013','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('14','PSPAO000014','2013','Kementerian','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('15','PSPAO000015','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('16','PSPAO000016','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('17','PSPAO000017','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('18','PSPAO000018','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('19','PSPAO000019','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('20','PSPAO000020','2013','Jabatan','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  
                  );

	return $data_1;
	
}



public function get_data_dummy_ketua_jabatan(){
	
	$data_1 =   array(
					array('1','PSPAO000001','2013','Kementerian','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  	array('2','PSPAO000002','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('3','PSPAO000003','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('4','PSPAO000004','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('5','PSPAO000005','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('6','PSPAO000006','2013','Agensi','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('7','PSPAO000007','2013','Kementerian','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('8','PSPAO000008','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('9','PSPAO000009','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('10','PSPAO000010','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('11','PSPAO000011','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('12','PSPAO000012','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('13','PSPAO000013','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('14','PSPAO000014','2013','Kementerian','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('15','PSPAO000015','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('16','PSPAO000016','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('17','PSPAO000017','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('18','PSPAO000018','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('19','PSPAO000019','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  array('20','PSPAO000020','2013','Jabatan','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ketuajab_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  
                  );

	return $data_1;
	
}

public function get_asetkhusus(){
	
	$data_1 =   array('Blok A','Blok B','Blok C','Blok D','Blok Kantin');

	return $data_1;
	
}

public function get_data_dummy_jkrpata2a(){
	
	$data_1 =   array(
					array('1','2,000.00','2,000.00','2,000.00','16,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('2','10,000.00','10,000.00','12,000.00','5,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('3','2,000.00','2,000.00','20,000.00','2,000.00','7,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('4','2,000.00','2,000.00','23,000.00','16,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('5','12,000.00','9,000.00','29,000.00','34,000.00','8,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('6','2,000.00','2,000.00','2,000.00','6,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('7','2,000.00','2,000.00','2,000.00','16,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('8','10,000.00','10,000.00','12,000.00','5,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('9','2,000.00','2,000.00','20,000.00','2,000.00','7,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('10','2,000.00','2,000.00','23,000.00','16,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('11','12,000.00','9,000.00','29,000.00','34,000.00','8,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('12','2,000.00','2,000.00','2,000.00','6,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('13','2,000.00','2,000.00','2,000.00','16,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('14','10,000.00','10,000.00','12,000.00','5,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('15','2,000.00','2,000.00','20,000.00','2,000.00','7,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('16','2,000.00','2,000.00','23,000.00','16,000.00','2,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('17','12,000.00','9,000.00','29,000.00','34,000.00','8,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
					array('18','2,000.00','2,000.00','2,000.00','6,000.00','4,000.00','<ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul>' ),
                  
                  );

	return $data_1;
	
}





public function get_data_dummy_all(){
	
	$data_1 =   array(
					array('1','PSPAO000001','2013','Kementerian','Mohd Kamil bin Ibrahim<br>(PP)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_pp_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href=""><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  	array('2','PSPAO000002','2013','Jabatan','Mohd Qoha bin Salehudin<br />(PTF)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('3','PSPAO000003','2013','Jabatan','Mohd Saleh bin Yaakob<br />(PPD)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ppd_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('4','PSPAO000004','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('5','PSPAO000005','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('6','PSPAO000006','2013','Agensi','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('7','PSPAO000007','2013','Kementerian','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('8','PSPAO000008','2013','Kementerian','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('9','PSPAO000009','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('10','PSPAO000010','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('11','PSPAO000011','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('12','PSPAO000012','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('13','PSPAO000013','2013','Agensi','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('14','PSPAO000014','2013','Kementerian','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('15','PSPAO000015','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('16','PSPAO000016','2013','Agensi','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('17','PSPAO000017','2013','Jabatan','Mohd Kamil bin Ibrahim<br>(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge">Deraf</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('18','PSPAO000018','2013','Jabatan','Mohd Qoha bin Salehudin<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-info">Sah</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('19','PSPAO000019','2013','Jabatan','Mohd Saleh bin Yaakob<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-inverse">Pembetulan</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  array('20','PSPAO000020','2013','Jabatan','Mohd Khairul bin Ramli<br />(Pegawai Teknikal Fasiliti)','02/01/2013','<span class="badge badge-warning">Semak</span>','<ul class="icomoon-icons-container"><a href="'.site_url('pspao/senarai_pspao_akhir_ptf_2').'"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe026;"></span> </li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe027;"></span></li></a></ul><ul class="icomoon-icons-container"><a href="#"><li class="rounded"><span class="fs1" aria-hidden="true" data-icon="&#xe0a7;"></span></li></a></ul>' ),
                  
                  );

	return $data_1;
	
}
   
    
}
